AWSTemplateFormatVersion: 2010-09-09
Description: |
  This CloudFormation Template for running Kittens Carousel Static Website on EC2. 
  Kittens Carousel Static Website will be deployed on Amazon Linux 2 
  EC2 Instance with custom security group which allows http connections on port 80 
  and ssh port 22 from aws or o2 ISP. Kittens Carousel Static Website is downloaded from 
  my Public Github repository, then deployed on Apache Web Server.
Resources:
  rSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: cfn-carousel-101-sg
      GroupName: cfn-carousel-101-sg
      SecurityGroupIngress:
        -   Description: o2 SSH 77.0.0.0/12
            CidrIp: 77.0.0.0/12
            IpProtocol: tcp 
            FromPort: 22
            ToPort: 22
        -   Description: o2 SSH 77.176.0.0/12
            CidrIp: 77.176.0.0/12
            IpProtocol: tcp 
            FromPort: 22
            ToPort: 22
        -   Description: o2 SSH 2a01:c00::/26
            CidrIpv6: 2a01:c00::/26
            IpProtocol: tcp 
            FromPort: 22
            ToPort: 22
        -   Description: aws SSH 
            CidrIp: 172.16.0.0/12
            IpProtocol: tcp 
            FromPort: 22
            ToPort: 22
        -   Description: o2 HTTP 77.0.0.0/12
            CidrIp: 77.0.0.0/12
            IpProtocol: tcp 
            FromPort: 80
            ToPort: 80
        -   Description: o2 HTTP 77.176.0.0/12
            CidrIp: 77.176.0.0/12
            IpProtocol: tcp 
            FromPort: 80
            ToPort: 80
        -   Description: o2 HTTP 2a01:c00::/26
            CidrIpv6: 2a01:c00::/26
            IpProtocol: tcp 
            FromPort: 80
            ToPort: 80
  rWebServer:
      Type: AWS::EC2::Instance
      Properties: 
        ImageId: ami-0022f774911c1d690
        InstanceType: t2.micro
        KeyName: ec2 
        SecurityGroupIds: 
          - !GetAtt rSecGroup.GroupId
        Tags: 
          - Key: Name
            Value: carousel-101-cfn
        UserData: 
            Fn::Base64: 
            |
              #!/bin/bash
              yum -y update
              yum -y install httpd
              chmod a+r /var/www/html
              cd /var/www/html
              wget https://raw.githubusercontent.com/de156397/aws-misc/main/projects/Project-101-kittens-carousel-static-website-ec2/static-web/{index.html,cat{0..2}.jpg,cat3.png}
              systemctl enable httpd
              systemctl start httpd
Outputs:
  WebsiteURL:
    Description: Kittens Carousel Application URL
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt rWebServer.PublicDnsName 